#+TITLE: Guix中文社区帮助文档

使用Guix的小伙伴们，有问题请来这里提问。

提问时请新建一个issue，并描述清楚你的问题。
参考：[[https://lug.ustc.edu.cn/wiki/doc/smart-questions][提问的智慧]]。

* 常见的问题

** 怎样设置中文输入法
你可以选择使用 ~ibus~ 或者 ~fcitx~ 。

*** 设置 ~ibus~
1. 安装 ~ibus~  和 ~ibus-libpinyin~ （或 ~ibus-rime~ ）。
   #+BEGIN_SRC scheme
     (operating-system
       (packages (cons* ibus ibus-rime dconf
                        %base-packages))
       ...
       )
   #+END_SRC
2. 设置以下的环境变量。bash用户添加到 ~/.profile 文件里，zsh用
   户添加到 ~/.zprofile 文件里。
   #+BEGIN_SRC sh
     export GTK_IM_MODULE="ibus"
     export QT_IM_MODULE="ibus"
     export XMODIFIERS="@im=ibus"
   #+END_SRC

   如果把 ~ibus~ 安装到system profile里，请设置以下的环境变量：
   #+BEGIN_SRC sh
     export GUIX_GTK2_IM_MODULE_FILE=/run/current-system/profile/lib/gtk-2.0/2.10.0/immodules-gtk2.cache
     export GUIX_GTK3_IM_MODULE_FILE=/run/current-system/profile/lib/gtk-3.0/3.0.0/immodules-gtk3.cache
   #+END_SRC
   如果把 ~ibus~ 安装到user profile里，与上面类似，请设置这些环境变量（但是作者
   没验证过是否可行）：
   #+BEGIN_SRC sh
     export GUIX_GTK2_IM_MODULE_FILE=$HOME/.guix-profile/lib/gtk-2.0/2.10.0/immodules-gtk2.cache
     export GUIX_GTK3_IM_MODULE_FILE=$HOME/.guix-profile/lib/gtk-3.0/3.0.0/immodules-gtk3.cache
   #+END_SRC
3. 如果你曾经安装过 ~ibus~ ，请删除 =~/.cache/ibus= 这个文件夹。不匹配的
   =~/.cache/ibus= 可能导致 ~ibus~ 无法启动。这是一个已知的bug。
   #+BEGIN_SRC shell
     rm -r ~/.cache/ibus
   #+END_SRC
4. 运行 ~ibus-daemon --xim --replace --daemonize~ 以启动 ~ibus-daemon~ 。
   #+BEGIN_SRC shell
     ibus-daemon --xim --replace --daemonize
   #+END_SRC
5. 运行 ~ibus-setup~ 进入设置图形界面，添加和设置输入法。
   #+BEGIN_SRC shell
     ibus-setup
   #+END_SRC
6. 好了，你可以使用 ~ibus~ 来输入中文了。

*重要：*
#+begin_quote
  如果 ~ibus~ 无法正常启动，请删除 =~/.cache/ibus= 之后再尝试一次。如果你更新了
  ~ibus~ 软件包，也需要删除 =~/.cache/ibus= 。这是一个已知的bug。
#+end_quote

*** 设置 ~fcitx~
@pmeiyu 不使用fcitx，此段略。

* 贡献

  - 你必须接受把你贡献的内容以下面的许可证发布。
  - 请克隆这个仓库，添加你的修改，然后提交Pull Request。

* 许可证

  除非另有说明，则：
  - 这个仓库里的代码以 [[https://www.gnu.org/licenses/gpl-3.0.en.html][GPLv3]] 许可证发布。
  - 这个仓库里的文档以 [[https://creativecommons.org/licenses/by-nc/4.0/legalcode][CC BY-NC v4.0]] 许可证发布。
